### ISSUE TITLE
[help wanted] Can not encrypt file

### ISSUE THREAD

**Issue by ducphd2** [tommmb/aes-python#1]
I ran your project, and I expected it can read and write file then encrypted that to other files, but I can't find the connection between `main.py` file and `aes.py` file.
Can you give me more information about your project?

**Comment by tommmb** [comment]
Hi mate, this is for a current school project so it is a work in progress.

The old `main.py` file was the GUI for the project and is unrelated to `aes.py`, you can ignore it.
